// Meeting storage — each meeting is a folder under data/meetings/<id>/ with:
//   meta.json       title, timestamps, status
//   transcript.json array of { t, text } segments (t = seconds from start)
//   notes.md        user's raw notes typed during/after the meeting
//   summary.md      LLM-generated notes
//   audio.wav       full meeting audio (16k mono s16le), if keepAudio is on
const fs = require("fs");
const path = require("path");

const DATA_DIR = path.join(__dirname, "..", "data");
const MEETINGS_DIR = path.join(DATA_DIR, "meetings");

function ensureDirs() {
  fs.mkdirSync(MEETINGS_DIR, { recursive: true });
}

function meetingDir(id) {
  // ids are generated by createMeeting; reject anything path-like
  if (!/^[a-z0-9-]+$/.test(id)) throw new Error("bad meeting id");
  return path.join(MEETINGS_DIR, id);
}

function createMeeting(title) {
  ensureDirs();
  const now = new Date();
  const id =
    now.toISOString().replace(/[:.]/g, "-").slice(0, 19).toLowerCase() +
    "-" +
    Math.floor(Math.random() * 1e6).toString(36);
  const dir = meetingDir(id);
  fs.mkdirSync(dir, { recursive: true });
  const meta = {
    id,
    title: title || "Meeting " + now.toLocaleString(),
    startedAt: now.toISOString(),
    endedAt: null,
    durationSec: 0,
    status: "recording",
  };
  fs.writeFileSync(path.join(dir, "meta.json"), JSON.stringify(meta, null, 2));
  fs.writeFileSync(path.join(dir, "transcript.json"), "[]");
  return meta;
}

function getMeta(id) {
  return JSON.parse(fs.readFileSync(path.join(meetingDir(id), "meta.json"), "utf8"));
}

function saveMeta(meta) {
  fs.writeFileSync(
    path.join(meetingDir(meta.id), "meta.json"),
    JSON.stringify(meta, null, 2)
  );
}

function listMeetings() {
  ensureDirs();
  return fs
    .readdirSync(MEETINGS_DIR)
    .filter((d) => fs.existsSync(path.join(MEETINGS_DIR, d, "meta.json")))
    .map((d) => JSON.parse(fs.readFileSync(path.join(MEETINGS_DIR, d, "meta.json"), "utf8")))
    .sort((a, b) => (a.startedAt < b.startedAt ? 1 : -1));
}

function getTranscript(id) {
  const p = path.join(meetingDir(id), "transcript.json");
  return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, "utf8")) : [];
}

function appendTranscript(id, segment) {
  const segs = getTranscript(id);
  segs.push(segment);
  fs.writeFileSync(path.join(meetingDir(id), "transcript.json"), JSON.stringify(segs, null, 1));
}

function readText(id, file) {
  const p = path.join(meetingDir(id), file);
  return fs.existsSync(p) ? fs.readFileSync(p, "utf8") : "";
}

function writeText(id, file, content) {
  fs.writeFileSync(path.join(meetingDir(id), file), content);
}

function getMeeting(id) {
  return {
    meta: getMeta(id),
    transcript: getTranscript(id),
    notes: readText(id, "notes.md"),
    summary: readText(id, "summary.md"),
  };
}

function deleteMeeting(id) {
  fs.rmSync(meetingDir(id), { recursive: true, force: true });
}

module.exports = {
  DATA_DIR,
  ensureDirs,
  meetingDir,
  createMeeting,
  getMeta,
  saveMeta,
  listMeetings,
  getTranscript,
  appendTranscript,
  readText,
  writeText,
  getMeeting,
  deleteMeeting,
};
