// Meeting storage — each meeting is a folder under data/meetings/<id>/ with:
//   meta.json       title, timestamps, status
//   transcript.json array of { t, text } segments (t = seconds from start)
//   notes.md        user's raw notes typed during/after the meeting
//   summary.md      LLM-generated notes
//   audio.wav       full meeting audio (16k mono s16le), if keepAudio is on
const fs = require("fs");
const path = require("path");

const DATA_DIR = path.join(__dirname, "..", "data");
const MEETINGS_DIR = path.join(DATA_DIR, "meetings");

function ensureDirs() {
  fs.mkdirSync(MEETINGS_DIR, { recursive: true });
}

// Atomic write: write to a temp file then rename over the target. rename(2) is
// atomic on the same filesystem, so a crash mid-write can never truncate or lose
// the existing file — readers see either the old bytes or the new, never partial.
function atomicWrite(filePath, data) {
  const tmp = filePath + ".tmp-" + process.pid;
  fs.writeFileSync(tmp, data);
  fs.renameSync(tmp, filePath);
}

function meetingDir(id) {
  // ids are generated by createMeeting; reject anything path-like
  if (!/^[a-z0-9-]+$/.test(id)) throw new Error("bad meeting id");
  return path.join(MEETINGS_DIR, id);
}

function createMeeting(title) {
  ensureDirs();
  const now = new Date();
  const id =
    now.toISOString().replace(/[:.]/g, "-").slice(0, 19).toLowerCase() +
    "-" +
    Math.floor(Math.random() * 1e6).toString(36);
  const dir = meetingDir(id);
  fs.mkdirSync(dir, { recursive: true });
  const meta = {
    id,
    title: title || "Meeting " + now.toLocaleString(),
    startedAt: now.toISOString(),
    endedAt: null,
    durationSec: 0,
    status: "recording",
  };
  fs.writeFileSync(path.join(dir, "meta.json"), JSON.stringify(meta, null, 2));
  fs.writeFileSync(path.join(dir, "transcript.json"), "[]");
  return meta;
}

function getMeta(id) {
  return JSON.parse(fs.readFileSync(path.join(meetingDir(id), "meta.json"), "utf8"));
}

function saveMeta(meta) {
  atomicWrite(
    path.join(meetingDir(meta.id), "meta.json"),
    JSON.stringify(meta, null, 2)
  );
}

function listMeetings() {
  ensureDirs();
  return fs
    .readdirSync(MEETINGS_DIR)
    .filter((d) => fs.existsSync(path.join(MEETINGS_DIR, d, "meta.json")))
    .map((d) => JSON.parse(fs.readFileSync(path.join(MEETINGS_DIR, d, "meta.json"), "utf8")))
    .sort((a, b) => (a.startedAt < b.startedAt ? 1 : -1));
}

function getTranscript(id) {
  const p = path.join(meetingDir(id), "transcript.json");
  return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, "utf8")) : [];
}

function appendTranscript(id, segment) {
  const segs = getTranscript(id);
  segs.push(segment);
  atomicWrite(path.join(meetingDir(id), "transcript.json"), JSON.stringify(segs, null, 1));
}

function readText(id, file) {
  const p = path.join(meetingDir(id), file);
  return fs.existsSync(p) ? fs.readFileSync(p, "utf8") : "";
}

function writeText(id, file, content) {
  atomicWrite(path.join(meetingDir(id), file), content);
}

function getVision(id) {
  const p = path.join(meetingDir(id), "vision.json");
  if (!fs.existsSync(p)) return null;
  try {
    return JSON.parse(fs.readFileSync(p, "utf8"));
  } catch {
    return null;
  }
}

function getMeeting(id) {
  return {
    meta: getMeta(id),
    transcript: getTranscript(id),
    notes: readText(id, "notes.md"),
    summary: readText(id, "summary.md"),
    vision: getVision(id),
  };
}

function deleteMeeting(id) {
  fs.rmSync(meetingDir(id), { recursive: true, force: true });
}

// Full-text search across every meeting's title, transcript, notes and summary.
// Returns the meeting meta plus a short snippet around the first match, and which
// field it matched in. Case-insensitive, plain substring (no regex surprises).
function searchMeetings(query) {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return [];
  const out = [];
  for (const meta of listMeetings()) {
    const speakerNames = Object.values(meta.speakers || {}).join(" ");
    const transcript = getTranscript(meta.id)
      .map((s) => s.text)
      .join(" ");
    const notes = readText(meta.id, "notes.md");
    const summary = readText(meta.id, "summary.md");
    // ordered so the most meaningful match wins the snippet
    const fields = [
      ["title", meta.title || ""],
      ["speakers", speakerNames],
      ["notes", notes],
      ["summary", summary],
      ["transcript", transcript],
    ];
    let hit = null;
    for (const [where, text] of fields) {
      const idx = text.toLowerCase().indexOf(q);
      if (idx !== -1) {
        hit = { where, snippet: snippetAround(text, idx, q.length) };
        break;
      }
    }
    if (hit) out.push({ ...meta, matchIn: hit.where, snippet: hit.snippet });
  }
  return out;
}

function snippetAround(text, idx, len) {
  const pad = 60;
  const start = Math.max(0, idx - pad);
  const end = Math.min(text.length, idx + len + pad);
  let s = text.slice(start, end).replace(/\s+/g, " ").trim();
  if (start > 0) s = "…" + s;
  if (end < text.length) s = s + "…";
  return s;
}

module.exports = {
  DATA_DIR,
  ensureDirs,
  meetingDir,
  createMeeting,
  getMeta,
  saveMeta,
  listMeetings,
  getTranscript,
  appendTranscript,
  readText,
  writeText,
  getVision,
  getMeeting,
  deleteMeeting,
  searchMeetings,
};
